import { useMemo, useState } from 'react'
import { Trash2 } from 'lucide-react'
import { ExportButtons } from '@/components/reports/ExportButtons'
import { Alert } from '@/components/ui/Alert'
import { Card } from '@/components/ui/Card'
import { DataTable, type Column } from '@/components/ui/DataTable'
import { Select, type SelectOption } from '@/components/ui/Select'
import { useAuth } from '@/hooks/useAuth'
import { useExportReport } from '@/hooks/useExportReport'
import { useCurrentStock, type StockRow } from '@/hooks/useReports'
import { useDeleteProduct } from '@/hooks/useProductMutations'
import { useConfirm } from '@/hooks/useConfirm'
import { useAlert } from '@/hooks/useAlert'
import { cn } from '@/lib/cn'
import { toUserMessage } from '@/lib/errors'
import type { ReportColumn, ReportMeta } from '@/lib/reportDocument'

/**
 * Current stock, and the two views of it that matter (SRD §7, §11).
 *
 * DSK-406 current stock, DSK-407 low stock, DSK-408 out of stock. They are one table with a
 * filter rather than three screens: same columns, same export, one place for a bug to live.
 */

type View = 'all' | 'low' | 'out'

const VIEW_OPTIONS: SelectOption[] = [
  { value: 'all', label: 'All products', description: 'Everything with a stock record' },
  { value: 'low', label: 'Low stock', description: 'At or below the minimum level' },
  { value: 'out', label: 'Out of stock', description: 'Nothing left' }
]

const TITLES: Record<View, string> = {
  all: 'Current stock report',
  low: 'Low stock report',
  out: 'Out of stock report'
}

/** Shared by the table and the exports, so a file can never disagree with the screen. */
const EXPORT_COLUMNS: ReportColumn<StockRow>[] = [
  { header: 'Product ID', value: (row) => row.productCode },
  { header: 'Product', value: (row) => row.productName },
  { header: 'Category', value: (row) => row.categoryName },
  { header: 'Brand', value: (row) => row.brandName },
  { header: 'Office', value: (row) => row.officeName },
  { header: 'Unit', value: (row) => row.uomCode },
  { header: 'Opening', value: (row) => row.openingQty, align: 'right' },
  { header: 'Inward', value: (row) => row.inwardQty, align: 'right' },
  { header: 'Outward', value: (row) => row.outwardQty, align: 'right' },
  { header: 'Current stock', value: (row) => row.qtyOnHand, align: 'right' },
  { header: 'Reserved', value: (row) => row.qtyReserved, align: 'right' },
  { header: 'Available', value: (row) => row.qtyAvailable, align: 'right' },
  { header: 'Minimum', value: (row) => row.minStock, align: 'right' }
]

export function Stock() {
  const { data, isPending, error, refetch } = useCurrentStock()
  const { exportExcel, exportPdf, isExporting, error: exportError } = useExportReport()
  const { session } = useAuth()
  const deleteProduct = useDeleteProduct()
  const confirm = useConfirm()
  const showAlert = useAlert()
  const [view, setView] = useState<View>('all')

  async function handleDelete(event: React.MouseEvent, row: StockRow) {
    event.stopPropagation()
    const ok = await confirm({
      title: 'Delete Product',
      description: `Are you sure you want to delete product "${row.productName}"? This action cannot be undone.`,
      confirmText: 'Delete Product'
    })
    if (!ok) return
    try {
      await deleteProduct.mutateAsync(row.productId)
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to delete product.'
      void showAlert({
        title: msg.includes('Cannot delete') ? 'Cannot Delete Item' : 'Action Failed',
        description: msg,
        tone: 'warning'
      })
    }
  }

  const rows = useMemo(() => {
    const all = data ?? []
    if (view === 'low') return all.filter((row) => row.isLowStock)
    if (view === 'out') return all.filter((row) => row.qtyAvailable <= 0)
    return all
  }, [data, view])

  // Report header facts (SRD §7) — printed above the table in the PDF so an exported sheet
  // says what it is, when it was run, over what, and by whom.
  const reportMeta = useMemo<ReportMeta>(() => {
    const offices = Array.from(new Set(rows.map((r) => r.officeName).filter((o): o is string => !!o)))
    const totalOnHand = rows.reduce((sum, r) => sum + r.qtyOnHand, 0)
    const totalAvailable = rows.reduce((sum, r) => sum + r.qtyAvailable, 0)
    return {
      title: TITLES[view],
      details: [
        { label: 'Generated', value: new Date().toLocaleString('en-IN') },
        { label: 'Generated by', value: session?.user.email ?? '—' },
        { label: 'Office', value: offices.length > 0 ? offices.join(', ') : 'All offices' },
        { label: 'View', value: VIEW_OPTIONS.find((o) => o.value === view)?.label ?? view },
        { label: 'Products', value: String(rows.length) },
        { label: 'Total current stock', value: String(totalOnHand) },
        { label: 'Total available', value: String(totalAvailable) }
      ]
    }
  }, [rows, view, session])

  const columns: Column<StockRow>[] = [
    {
      id: 'productId',
      header: 'Product ID',
      width: 'w-28',
      cell: (row) => (
        <span className="font-mono text-mono-id text-on-surface-variant">{row.productCode}</span>
      )
    },
    {
      id: 'product',
      header: 'Product',
      cell: (row) => (
        <div className="flex flex-col">
          <span className="font-semibold text-on-surface">{row.productName}</span>
          <span className="text-body-sm text-on-surface-variant/60">
            {row.categoryName ?? '—'}
            {row.officeName === null ? '' : ` · ${row.officeName}`}
          </span>
        </div>
      )
    },
    {
      id: 'opening',
      header: 'Opening',
      align: 'right',
      width: 'w-24',
      cell: (row) => <span className="tabular-nums text-on-surface-variant/70">{row.openingQty}</span>
    },
    {
      id: 'inward',
      header: 'Inward',
      align: 'right',
      width: 'w-24',
      // Green: stock that came in. Colour reinforces the number, never replaces it.
      cell: (row) => (
        <span className="tabular-nums text-success">
          {row.inwardQty > 0 ? `+${row.inwardQty}` : row.inwardQty}
        </span>
      )
    },
    {
      id: 'outward',
      header: 'Outward',
      align: 'right',
      width: 'w-24',
      cell: (row) => (
        <span className="tabular-nums text-error">
          {row.outwardQty > 0 ? `-${row.outwardQty}` : row.outwardQty}
        </span>
      )
    },
    {
      id: 'onHand',
      header: 'Current stock',
      align: 'right',
      width: 'w-28',
      cell: (row) => (
        <span className="font-semibold tabular-nums text-on-surface">{row.qtyOnHand}</span>
      )
    },
    {
      id: 'reserved',
      header: 'Reserved',
      align: 'right',
      width: 'w-24',
      // Reservation is a future feature — shown for completeness, currently always 0.
      cell: (row) => (
        <span className="tabular-nums text-on-surface-variant/60">{row.qtyReserved}</span>
      )
    },
    {
      id: 'available',
      header: 'Available',
      align: 'right',
      width: 'w-28',
      cell: (row) => (
        <span
          className={cn(
            'font-semibold tabular-nums',
            row.qtyAvailable <= 0
              ? 'text-error'
              : row.isLowStock
                ? 'text-tertiary'
                : 'text-on-surface'
          )}
        >
          {row.qtyAvailable}
          {row.uomCode === null ? null : (
            <span className="ml-1 text-body-sm font-normal text-on-surface-variant/60">
              {row.uomCode}
            </span>
          )}
        </span>
      )
    },
    {
      id: 'min',
      header: 'Minimum',
      align: 'right',
      width: 'w-24',
      // Colour alone never carries meaning — this column states the same fact as a number.
      cell: (row) => <span className="tabular-nums text-on-surface-variant/70">{row.minStock}</span>
    },
    {
      id: 'actions',
      header: 'Actions',
      align: 'right',
      width: 'w-20',
      cell: (row) => (
        <button
          onClick={(e) => void handleDelete(e, row)}
          disabled={deleteProduct.isPending}
          className="inline-flex items-center justify-center rounded-lg p-1.5 text-error transition-colors hover:bg-error/10 disabled:opacity-50"
          title="Delete product"
        >
          <Trash2 aria-hidden="true" className="size-4" />
        </button>
      )
    }
  ]

  return (
    <div className="flex flex-col gap-gutter">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-h1 text-on-surface">Stock</h1>
          <p className="text-body-sm text-on-surface-variant/60">
            {isPending ? 'Loading…' : `${rows.length} of ${data?.length ?? 0} records`}
          </p>
        </div>

        <ExportButtons
          columns={EXPORT_COLUMNS}
          isExporting={isExporting}
          meta={reportMeta}
          onExcel={(r, c, m) => void exportExcel(r, c, m)}
          onPdf={(r, c, m) => void exportPdf(r, c, m)}
          rows={rows}
        />
      </div>

      {exportError === null ? null : <Alert tone="error">{exportError}</Alert>}

      <Card>
        <div className="flex items-end gap-3 hairline-b p-4">
          <Select
            containerClassName="w-64"
            label="Show"
            onChange={(next) => setView(next as View)}
            options={VIEW_OPTIONS}
            value={view}
          />
        </div>

        <DataTable
          caption="Current stock by product"
          columns={columns}
          emptyMessage={
            view === 'low'
              ? 'No products are below their minimum level.'
              : view === 'out'
                ? 'Nothing is out of stock.'
                : 'No stock records yet. Receive stock on the Inward screen.'
          }
          error={error === null ? undefined : toUserMessage(error)}
          getRowId={(row) => `${row.productId}-${row.officeName ?? ''}`}
          isLoading={isPending}
          onRetry={() => void refetch()}
          rows={rows}
        />
      </Card>
    </div>
  )
}
